### ISSUE TITLE
Read configuration from a file insted of hardcoding values in the source code

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/front_basicrum_go#4]
At the moment the code is still in a proof of concpet stage and we have buch of hardcoded information about:

* Database connection
* Server settings (port, host ...)

The plan is to move this to cofiguration to YAML file.

Example: startup_config.yaml
```
server:
  host: "localhost"
  port: 8087

database:
  address: "localhost"
  port: 9000
  database_name: "default"
  username: "default"
  password: ""

persistance:
  db_strategy: all_hosts_in_one_db
  table_strategy: all_hosts_in_one_table
```
