### ISSUE TITLE
Use ENV variables for passing configuration instead of reading from YAML file

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/front_basicrum_go#47]
Today we read the application configuration from `startup_config.yaml`. We would like to change this and to use environmental variables instead.

For reference this is my version of `startup_config.yaml`:
```
server:
  host: "localhost"
  port: 8087

database:
  host: "localhost"
  port: 9000
  database_name: "default"
  username: "default"
  password: ""
  table_prefix: "integration_test"

persistance:
  database_strategy: all_in_one_db
  table_strategy: all_in_one_table

backup:
  enabled: true
  directory: "/home/tsvetan/projects/basicrum/front_basicrum_go/data_archive/"
  interval_seconds: 5
```

When we start substituting the YAML config we will need to follow this convention:

E.g.
```
server:
  host: "localhost"
  port: 8087
```

Will become:
```
SERVER_HOST=localhost
SERVER_PORT=8087
```

Couple of more things to do:

- [ ]  Change the part of the **README.MD** where we have references to the YAML configuration.
- [ ]  Add an example how the configuration could be passed in a docker compose file.
- [ ]  Keep in mind that the integration tests depend on `startup_config.yaml` ... they will need to be refactored in order to read from environment variables.
